export declare class Plans {
    static modelName: string;
    static Cols: {
        place_id: string;
        title: string;
        placeSpan: string;
        placeStartTime: string;
        placeEndTime: string;
        tags: string;
        imageUrl: string;
        memo: string;
        transportationMode: string;
        transportationDepartureTime: string;
        transportationArrivalTime: string;
        transportationSpan: string;
        avoidFerries: string;
        avoidHighways: string;
        avoidTolls: string;
        transitModes: string;
        transitRoutingPreference: string;
        createdAt: string;
        updatedAt: string;
    };
    static fromJSON(json: any): Plans;
    place_id?: string;
    title: string;
    placeSpan: Date;
    placeStartTime: Date;
    placeEndTime: Date;
    tags: Array<string>;
    imageUrl?: string;
    memo?: string;
    transportationMode?: string;
    transportationDepartureTime?: Date;
    transportationArrivalTime?: Date;
    transportationSpan: Date;
    avoidFerries: boolean;
    avoidHighways: boolean;
    avoidTolls: boolean;
    transitModes: string;
    transitRoutingPreference: string;
    createdAt: Date;
    updatedAt: Date;
}
