name: push spelieve bacjend common files

on:
  push:
    branches:
      - 'main'
    paths:
      - 'Backend/**'
  workflow_dispatch:

jobs:
  makePRBackendCommon:
    strategy:
      matrix:
        repo: ['Ayato-kosaka/spelieve-backend-tag', 'Ayato-kosaka/spelieve-backend-place']
    name: makePRBackendCommon
    runs-on: ubuntu-latest
    steps:
      - name: dispatch backend-common-updated
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ matrix.repo }}
          event-type: backend-common-updated