name: publish spelieve library

env:
 CI: true

on:
 schedule:
  - cron: '0 19 * * *'
 workflow_dispatch:

jobs:
 publish:
   name: Truncate
   runs-on: ubuntu-latest
   steps:
     - name: checkout
       uses: actions/checkout@v2
    
     # Nodeのバージョンを指定
     - name: setup node
       uses: actions/setup-node@v1
       with:
         node-version: 14.x
         registry-url: https://registry.npmjs.org
        
     # バージョンを更新
     - name: update version
       run: |
        git config user.name github-actions[bot]
        git config user.email 41898282+github-actions[bot]@users.noreply.github.com
        npm version patch

     # 必要なモジュールをインストール
     - name: install node_modules
       run: npm install

    # spelieve-gulp を実行
     - name: run spelieve-gulp
       run: npm run regen
       env:
         PG_DATA_ENDPOINT: ${{ secrets.PG_DATA_ENDPOINT }}

     # Eslint Prettier を実行
     # - name: build
       # run: npx tsc

    # lib を削除する
     - name: run clean

    # typescript をコンパイルし、lib に配置する
     - name: run tsc
       run: npm run tsc

     # パッケージとして公開する
     - name: publish
       run: npx can-npm-publish --verbose && npm publish --access=public || echo "No need to publish"
       env:
         NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
        
     # バージョン情報を環境変数として設定
     - name: set version to env
       run: node -p -e '`VERSION=${require("./package.json").version}`' >> $GITHUB_ENV

     # バージョン情報持つタグを付与する
     - name: add version tag
       uses: pkgdeps/git-tag-action@v2
       with:
         version: ${{ env.VERSION }}
         github_token: ${{ secrets.GITHUB_TOKEN }}
         github_repo: ${{ github.repository }}
         git_commit_sha: ${{ github.sha }}
         git_tag_prefix: "v"
 
     # プシュする
     - name: push changes
       run: |
        git add -A
        git commit -m "truncate ${VERSION}"
        git push origin main
